version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: geochangesdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
     ConnectionStrings__DefaultConnection: "Server=mariadb;Database=geochangesdb;User=root;Password=123"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
